# Generated by Django 5.2 on 2025-05-15 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_post_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='texto',
            new_name='conteudo',
        ),
        migrations.AlterField(
            model_name='comentario',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='base.post'),
        ),
    ]
