# Generated by Django 5.2 on 2025-05-18 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_texto_comentario_conteudo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.produto'),
        ),
    ]
