# Generated by Django 5.2 on 2025-05-18 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='quantidade',
            field=models.IntegerField(default=1),
        ),
    ]
